import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'features/gas_log/domain/entities/gas_log.dart';
import 'features/gas_log/data/model/gas_log_record.dart';
import 'features/gas_log/data/repositories/gas_log_hive_repository.dart';

/// Complete setup example for Gas Log app with Hive database
///
/// This class demonstrates the complete architecture and usage pattern for a gas log
/// application using Hive as the local database with clean architecture principles.
///
/// Architecture Components:
/// - GasLog: Domain model used in UI and business logic
/// - GasLogRecord: Data model saved to Hive database with type adapters
/// - GasLogMapper: Converts between domain and data models seamlessly
/// - GasLogHiveRepository: Handles all database operations with error handling
///
/// Key Features:
/// - Auto-generated unique IDs for new records
/// - Efficient key-value storage using Hive
/// - Clean separation between domain and data layers
/// - Type-safe database operations with compile-time checking
/// - Easy cloud synchronization (single .hive file)
class GasLogAppSetup {
  /// Initialize Hive database and register type adapters
  ///
  /// This method must be called in main() before running the Flutter app.
  /// It performs the following initialization steps:
  /// 1. Initializes Hive for Flutter (sets up local storage paths)
  /// 2. Registers the auto-generated GasLogRecord adapter for type safety
  /// 3. Opens the gas logs database box for immediate use
  ///
  /// Throws: Exception if Hive initialization fails
  ///
  /// Example usage:
  /// ```dart
  /// void main() async {
  ///   WidgetsFlutterBinding.ensureInitialized();
  ///   await GasLogAppSetup.initializeHive();
  ///   runApp(MyApp());
  /// }
  /// ```
  static Future<void> initializeHive() async {
    // Initialize Hive for Flutter (sets up platform-specific storage paths)
    await Hive.initFlutter();

    // Register the GasLogRecord adapter (auto-generated by build_runner)
    // This enables type-safe serialization/deserialization of GasLogRecord objects
    Hive.registerAdapter(GasLogRecordAdapter());

    // Initialize the repository by opening the gas logs database box
    // This creates the database file if it doesn't exist
    await GasLogHiveRepository.init();

    print('✅ Hive database initialized successfully');
  }

  /// Comprehensive demonstration of the gas log system functionality
  ///
  /// This method showcases all major operations available in the gas log system:
  /// - Creating new gas log entries with domain models
  /// - Saving entries to the database (automatic ID generation)
  /// - Retrieving all entries with automatic sorting by date
  /// - Finding specific entries by ID
  /// - Updating existing entries
  /// - Querying entries by date range
  ///
  /// All operations demonstrate the clean separation between domain models
  /// (used in business logic) and data models (stored in Hive database).
  ///
  /// This method is useful for:
  /// - Testing the complete system functionality
  /// - Understanding the API usage patterns
  /// - Verifying database operations work correctly
  static Future<void> demonstrateUsage() async {
    final repository = GasLogHiveRepository();

    print('🚀 Starting Gas Log demonstration...');

    // 1. Create new gas logs using clean domain models
    // These models represent the business logic layer and are used throughout the UI
    final gasLog1 = GasLog(
      odometer: '45,230', // Current vehicle mileage
      distance: 320.5, // Miles driven since last fill-up
      gas: 42.3, // Gallons of gas purchased
      price: 3.89, // Price per gallon
      date: DateTime.now().subtract(
        Duration(days: 5),
      ), // When the fill-up occurred
      gasStation: 'Shell Station', // Optional: where the gas was purchased
      comment: 'Regular unleaded fuel', // Optional: additional notes
    );

    final gasLog2 = GasLog(
      odometer: '45,550', // Updated mileage after driving
      distance: 285.2, // Shorter trip this time
      gas: 38.7, // Less gas needed
      price: 3.95, // Slightly higher price
      date: DateTime.now().subtract(Duration(days: 2)), // More recent fill-up
      gasStation: 'Exxon', // Different gas station
      comment: 'Premium fuel', // Used premium gas this time
    );

    // 2. Save gas logs to the database
    // The repository automatically:
    // - Generates unique IDs for new records
    // - Converts domain models to data models using the mapper
    // - Stores the data in Hive using efficient key-value storage
    String savedId1 = await repository.saveGasLog(gasLog1);
    String savedId2 = await repository.saveGasLog(gasLog2);

    print('💾 Saved gas logs with IDs: $savedId1, $savedId2');

    // 3. Retrieve all gas logs from the database
    // The repository automatically:
    // - Fetches all records from Hive
    // - Converts data models back to domain models
    // - Sorts by date (newest first) for convenient display
    List<GasLog> allLogs = await repository.getGasLogs();
    print('📋 Retrieved ${allLogs.length} gas logs from database');

    // 4. Display gas logs (UI layer receives clean domain models)
    // This demonstrates how the UI only works with domain models,
    // never needing to know about the underlying data storage format
    for (var log in allLogs) {
      print('🚗 ${log.odometer} miles - ${log.gas} gallons - \$${log.price}');
    }

    // 5. Get a specific gas log by ID
    // Demonstrates efficient key-based lookup using the generated ID
    GasLog specificLog = await repository.getGasLog(savedId1);
    print('🔍 Found specific log: ${specificLog.odometer} miles');

    // 6. Update an existing gas log
    // Shows how to modify records using the copyWith pattern
    // The same saveGasLog method handles both create and update operations
    final updatedLog = specificLog.copyWith(
      comment: 'Updated comment - filled up completely',
    );
    await repository.saveGasLog(updatedLog);
    print('✏️ Updated gas log comment');

    // 7. Query gas logs by date range
    // Demonstrates advanced querying capabilities for reporting features
    List<GasLog> currentMonthLogs = await repository.getCurrentMonthGasLogs();
    print('📅 Current month has ${currentMonthLogs.length} gas logs');

    print('✅ Demonstration completed successfully!');
  }
}

/// Complete Flutter widget demonstrating gas log management with Hive database
///
/// This widget provides a full-featured user interface for managing gas logs with:
/// - Real-time data loading and display
/// - Add new gas log entries with sample data
/// - Delete gas logs with confirmation dialogs
/// - View detailed information for each gas log
/// - Responsive UI with loading states and error handling
/// - Material Design components for professional appearance
///
/// Key Features:
/// - **State Management**: Uses StatefulWidget for reactive UI updates
/// - **Error Handling**: Comprehensive try-catch blocks with user feedback
/// - **Loading States**: Shows progress indicators during async operations
/// - **Empty States**: Helpful messaging when no data is available
/// - **Confirmation Dialogs**: Prevents accidental data deletion
/// - **Responsive Design**: Adapts to different screen sizes and orientations
///
/// Architecture Integration:
/// - Works exclusively with GasLog domain models
/// - Uses GasLogHiveRepository for all database operations
/// - Demonstrates clean separation between UI and data layers
/// - Shows proper error handling and user feedback patterns
///
/// Usage:
/// ```dart
/// Navigator.push(context, MaterialPageRoute(
///   builder: (context) => GasLogScreen(),
/// ));
/// ```
class GasLogScreen extends StatefulWidget {
  const GasLogScreen({super.key});

  @override
  _GasLogScreenState createState() => _GasLogScreenState();
}

/// State class for GasLogScreen with comprehensive gas log management functionality
///
/// This class handles:
/// - Loading and displaying gas logs from the database
/// - Adding new sample gas logs for testing/demonstration
/// - Deleting gas logs with user confirmation
/// - Error handling and user feedback via SnackBars
/// - UI state management (loading, empty, populated states)
class _GasLogScreenState extends State<GasLogScreen> {
  /// Repository instance for all database operations
  /// Uses the Hive-based implementation for local storage
  final GasLogHiveRepository _repository = GasLogHiveRepository();

  /// List of gas logs currently displayed in the UI
  /// Automatically updated when data changes in the database
  List<GasLog> _gasLogs = [];

  /// Loading state indicator to show progress during async operations
  /// Prevents user interaction while data is being loaded or saved
  bool _isLoading = true;

  /// Widget lifecycle initialization
  /// Called once when the widget is inserted into the widget tree
  /// Immediately starts loading gas logs from the database
  @override
  void initState() {
    super.initState();
    _loadGasLogs(); // Load initial data
  }

  /// Load all gas logs from the database and update the UI
  ///
  /// This method:
  /// 1. Sets loading state to show progress indicator
  /// 2. Fetches all gas logs from the repository
  /// 3. Updates the UI with the loaded data
  /// 4. Handles any errors that occur during loading
  /// 5. Always clears the loading state when complete
  ///
  /// The repository automatically sorts gas logs by date (newest first)
  /// and converts data models to domain models for UI consumption.
  Future<void> _loadGasLogs() async {
    try {
      // Show loading indicator while fetching data
      setState(() => _isLoading = true);

      // Fetch all gas logs from the Hive database
      // Repository handles conversion from GasLogRecord to GasLog
      final logs = await _repository.getGasLogs();

      // Update UI with loaded data and clear loading state
      setState(() {
        _gasLogs = logs;
        _isLoading = false;
      });
    } catch (e) {
      // Handle any database or network errors
      setState(() => _isLoading = false);
      _showError('Failed to load gas logs: $e');
    }
  }

  /// Add a new sample gas log for testing and demonstration purposes
  ///
  /// This method creates realistic sample data with:
  /// - Progressive odometer readings (increasing mileage)
  /// - Varied distance, gas, and price values
  /// - Different dates (going backwards in time)
  /// - Unique gas station names and comments
  ///
  /// The sample data helps demonstrate:
  /// - How new records are created and saved
  /// - Auto-generation of unique IDs
  /// - Immediate UI updates after saving
  /// - Success feedback to the user
  Future<void> _addSampleGasLog() async {
    // Create a new gas log with realistic sample data
    // Values are calculated based on existing log count for variety
    final newLog = GasLog(
      odometer: '${45000 + _gasLogs.length * 300}', // Progressive mileage
      distance: 250 + (_gasLogs.length * 10).toDouble(), // Varying distances
      gas: 40.0 + (_gasLogs.length * 2), // Different gas amounts
      price: 3.50 + (_gasLogs.length * 0.1), // Fluctuating prices
      date: DateTime.now().subtract(
        Duration(days: _gasLogs.length),
      ), // Past dates
      gasStation:
          'Sample Station ${_gasLogs.length + 1}', // Unique station names
      comment: 'Sample gas log #${_gasLogs.length + 1}', // Numbered comments
    );

    try {
      // Save the new gas log to the database
      // Repository automatically generates ID and handles data conversion
      await _repository.saveGasLog(newLog);

      // Refresh the UI to show the new log
      _loadGasLogs();

      // Show success feedback to the user
      _showSuccess('Gas log added successfully');
    } catch (e) {
      // Handle any errors during save operation
      _showError('Failed to add gas log: $e');
    }
  }

  /// Delete a specific gas log from the database
  ///
  /// This method:
  /// 1. Validates that the gas log has a valid ID
  /// 2. Attempts to delete the record from the database
  /// 3. Refreshes the UI if deletion is successful
  /// 4. Shows appropriate feedback to the user
  /// 5. Handles any errors that occur during deletion
  ///
  /// @param gasLog The gas log to delete (must have a non-null ID)
  Future<void> _deleteGasLog(GasLog gasLog) async {
    // Ensure the gas log has a valid ID before attempting deletion
    if (gasLog.id == null) return;

    try {
      // Attempt to delete the gas log from the database
      // Repository uses the ID as the key for efficient deletion
      bool deleted = await _repository.deleteGasLog(gasLog.id!);

      if (deleted) {
        // Deletion successful - refresh UI and show confirmation
        _loadGasLogs();
        _showSuccess('Gas log deleted');
      } else {
        // Gas log not found in database
        _showError('Gas log not found');
      }
    } catch (e) {
      // Handle any errors during deletion
      _showError('Failed to delete gas log: $e');
    }
  }

  /// Display an error message to the user using a red SnackBar
  ///
  /// @param message The error message to display
  void _showError(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: Colors.red, // Red background indicates error
      ),
    );
  }

  /// Display a success message to the user using a green SnackBar
  ///
  /// @param message The success message to display
  void _showSuccess(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: Colors.green, // Green background indicates success
      ),
    );
  }

  /// Build the main UI for the gas log screen
  ///
  /// This method creates a comprehensive user interface with:
  /// - App bar with title showing gas log count and refresh button
  /// - Three main UI states: loading, empty, and populated
  /// - Floating action button for adding new gas logs
  /// - Responsive design that adapts to different screen sizes
  ///
  /// UI States:
  /// 1. **Loading State**: Shows circular progress indicator with text
  /// 2. **Empty State**: Shows helpful message with gas station icon
  /// 3. **Populated State**: Shows scrollable list of gas log cards
  ///
  /// Each gas log card displays:
  /// - Odometer reading as the main title
  /// - Gas amount, price, distance, and date as subtitle
  /// - Optional gas station and comment information
  /// - Delete button with confirmation dialog
  /// - Tap handler for detailed view dialog
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // App bar with dynamic title showing gas log count
      appBar: AppBar(
        title: Text('Gas Logs (${_gasLogs.length})'), // Shows current count
        backgroundColor: Colors.blue,
        foregroundColor: Colors.white,
        actions: [
          // Refresh button to manually reload data
          IconButton(
            icon: Icon(Icons.refresh),
            onPressed: _loadGasLogs, // Reload all gas logs
            tooltip: 'Refresh',
          ),
        ],
      ),
      // Main body with conditional rendering based on state
      body: _isLoading
          ? // Loading State: Show progress indicator with explanatory text
            Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  CircularProgressIndicator(), // Material Design spinner
                  SizedBox(height: 16),
                  Text('Loading gas logs...'), // User-friendly loading message
                ],
              ),
            )
          : _gasLogs.isEmpty
          ? // Empty State: Encourage user to add their first gas log
            Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  // Large gas station icon for visual appeal
                  Icon(Icons.local_gas_station, size: 64, color: Colors.grey),
                  SizedBox(height: 16),
                  // Prominent heading
                  Text(
                    'No gas logs yet',
                    style: Theme.of(context).textTheme.headlineSmall,
                  ),
                  SizedBox(height: 8),
                  // Helpful instruction text
                  Text('Tap the + button to add your first gas log'),
                ],
              ),
            )
          : // Populated State: Show scrollable list of gas log cards
            ListView.builder(
              padding: EdgeInsets.all(8.0), // Consistent padding around list
              itemCount: _gasLogs.length,
              itemBuilder: (context, index) {
                final log = _gasLogs[index];
                return Card(
                  elevation: 2, // Subtle shadow for depth
                  margin: EdgeInsets.symmetric(
                    vertical: 4,
                  ), // Spacing between cards
                  child: ListTile(
                    // Leading icon with consistent branding
                    leading: CircleAvatar(
                      backgroundColor: Colors.blue,
                      child: Icon(Icons.local_gas_station, color: Colors.white),
                    ),
                    // Main title: odometer reading with bold formatting
                    title: Text(
                      '${log.odometer} miles',
                      style: TextStyle(fontWeight: FontWeight.bold),
                    ),
                    // Subtitle: comprehensive gas log information
                    subtitle: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        // Primary information: gas amount and price
                        Text(
                          '${log.gas.toStringAsFixed(1)} gal • \$${log.price.toStringAsFixed(2)}',
                        ),
                        // Secondary information: distance and date
                        Text(
                          '${log.distance.toStringAsFixed(1)} miles • ${log.date.toString().split(' ')[0]}',
                        ),
                        // Optional information: gas station (if provided)
                        if (log.gasStation?.isNotEmpty == true)
                          Text('📍 ${log.gasStation}'),
                        // Optional information: comment (if provided)
                        if (log.comment?.isNotEmpty == true)
                          Text(
                            '💬 ${log.comment}',
                            style: TextStyle(fontStyle: FontStyle.italic),
                          ),
                      ],
                    ),
                    // Trailing delete button with confirmation
                    trailing: IconButton(
                      icon: Icon(Icons.delete, color: Colors.red),
                      onPressed: () => _showDeleteConfirmation(log),
                      tooltip: 'Delete',
                    ),
                    // Tap handler for detailed view
                    onTap: () => _showGasLogDetails(log),
                  ),
                );
              },
            ),
      // Floating action button for adding new gas logs
      floatingActionButton: FloatingActionButton(
        onPressed: _addSampleGasLog, // Add sample data for testing
        backgroundColor: Colors.blue,
        tooltip: 'Add Gas Log',
        child: Icon(Icons.add, color: Colors.white),
      ),
    );
  }

  /// Show a confirmation dialog before deleting a gas log
  ///
  /// This method provides a safety mechanism to prevent accidental deletions
  /// by requiring explicit user confirmation. The dialog includes:
  /// - Clear title and message explaining the action
  /// - Cancel button to abort the operation
  /// - Delete button with red text to indicate destructive action
  ///
  /// @param gasLog The gas log that will be deleted if confirmed
  void _showDeleteConfirmation(GasLog gasLog) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: Text('Delete Gas Log'), // Clear dialog title
        content: Text(
          'Are you sure you want to delete this gas log?',
        ), // Confirmation message
        actions: [
          // Cancel button - safe default action
          TextButton(
            onPressed: () =>
                Navigator.pop(context), // Close dialog without action
            child: Text('Cancel'),
          ),
          // Delete button - destructive action with red color
          TextButton(
            onPressed: () {
              Navigator.pop(context); // Close dialog first
              _deleteGasLog(gasLog); // Then perform deletion
            },
            child: Text('Delete', style: TextStyle(color: Colors.red)),
          ),
        ],
      ),
    );
  }

  /// Show a detailed view dialog for a specific gas log
  ///
  /// This method displays all available information about a gas log in a
  /// well-organized dialog format. The dialog includes:
  /// - All gas log fields with proper labels
  /// - Conditional display of optional fields
  /// - Consistent formatting and spacing
  /// - Close button for easy dismissal
  ///
  /// The detailed view helps users:
  /// - Review complete gas log information
  /// - Verify data accuracy
  /// - Copy information if needed
  ///
  /// @param gasLog The gas log to display in detail
  void _showGasLogDetails(GasLog gasLog) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: Text('Gas Log Details'), // Dialog title
        content: Column(
          mainAxisSize: MainAxisSize.min, // Size dialog to content
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Display all gas log fields with consistent formatting
            _buildDetailRow('ID', gasLog.id ?? 'N/A'), // Unique identifier
            _buildDetailRow(
              'Odometer',
              '${gasLog.odometer} miles',
            ), // Vehicle mileage
            _buildDetailRow(
              'Distance',
              '${gasLog.distance.toStringAsFixed(1)} miles',
            ), // Trip distance
            _buildDetailRow(
              'Gas',
              '${gasLog.gas.toStringAsFixed(1)} gallons',
            ), // Fuel amount
            _buildDetailRow(
              'Price',
              '\$${gasLog.price.toStringAsFixed(2)}',
            ), // Fuel price
            _buildDetailRow(
              'Date',
              gasLog.date.toString().split(' ')[0],
            ), // Fill-up date
            // Conditional display of optional fields
            if (gasLog.gasStation?.isNotEmpty == true)
              _buildDetailRow(
                'Station',
                gasLog.gasStation!,
              ), // Gas station name
            if (gasLog.comment?.isNotEmpty == true)
              _buildDetailRow('Comment', gasLog.comment!), // Additional notes
          ],
        ),
        actions: [
          // Close button to dismiss the dialog
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: Text('Close'),
          ),
        ],
      ),
    );
  }

  /// Build a consistently formatted detail row for the gas log details dialog
  ///
  /// This helper method creates uniform spacing and formatting for each
  /// field in the details view. Each row contains:
  /// - Bold label with fixed width for alignment
  /// - Value text that can wrap if needed
  /// - Consistent vertical spacing
  ///
  /// @param label The field name (e.g., "Odometer", "Price")
  /// @param value The field value (e.g., "45,230 miles", "$3.89")
  /// @return A formatted widget for display in the details dialog
  Widget _buildDetailRow(String label, String value) {
    return Padding(
      padding: EdgeInsets.symmetric(vertical: 4), // Consistent vertical spacing
      child: Row(
        crossAxisAlignment:
            CrossAxisAlignment.start, // Align to top for long text
        children: [
          // Fixed-width label column for consistent alignment
          SizedBox(
            width: 80, // Fixed width ensures labels align vertically
            child: Text(
              '$label:', // Add colon to separate label from value
              style: TextStyle(
                fontWeight: FontWeight.bold,
              ), // Bold labels for emphasis
            ),
          ),
          // Flexible value column that can wrap text if needed
          Expanded(child: Text(value)), // Expanded allows text to wrap
        ],
      ),
    );
  }
}
