// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTnSCaqFCucwTBd0cRIgVyX2tMBbCKYLg',
    appId: '1:486015857737:web:b2d07691fd947c8ae63b98',
    messagingSenderId: '486015857737',
    projectId: 'home-made-message',
    authDomain: 'home-made-message.firebaseapp.com',
    storageBucket: 'home-made-message.firebasestorage.app',
    measurementId: 'G-EQNP9R3VD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiZZYLa_E7TAzHuGHatXMZlOuTmpRGk0U',
    appId: '1:486015857737:android:4be4c34511fb60f7e63b98',
    messagingSenderId: '486015857737',
    projectId: 'home-made-message',
    storageBucket: 'home-made-message.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPKD-oAk-EB3xxyBBXA3_Hj0kju1GdfUQ',
    appId: '1:486015857737:ios:daf7a375fa5719cbe63b98',
    messagingSenderId: '486015857737',
    projectId: 'home-made-message',
    storageBucket: 'home-made-message.firebasestorage.app',
    iosBundleId: 'com.pivotpointsol.hmmConsole',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTnSCaqFCucwTBd0cRIgVyX2tMBbCKYLg',
    appId: '1:486015857737:web:57cfc1e62a9d84a5e63b98',
    messagingSenderId: '486015857737',
    projectId: 'home-made-message',
    authDomain: 'home-made-message.firebaseapp.com',
    storageBucket: 'home-made-message.firebasestorage.app',
    measurementId: 'G-TBE59H5QR9',
  );
}
